stages:
  - deploy

deploy_to_server:
  stage: deploy
  image: debian
  before_script:
    - echo "Installing dependencies..."
    # Add Docker's official GPG key:
    - apt update
    - apt install ca-certificates curl
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    - chmod a+r /etc/apt/keyrings/docker.asc
    # Add the repository to Apt sources:
    - |
      tee /etc/apt/sources.list.d/docker.sources <<EOF
      Types: deb
      URIs: https://download.docker.com/linux/debian
      Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
      Components: stable
      Architectures: $(dpkg --print-architecture)
      Signed-By: /etc/apt/keyrings/docker.asc
      EOF
    - apt update
    - apt install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - echo "Creating the .ssh folder..."
    - mkdir -p ~/.ssh
    - echo "Putting the SSH Private key in the wallet..."
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - echo "Changing the permissions for the SSH Private key..."
    - chmod 600 ~/.ssh/id_ed25519
    # - echo "Starting SSH key scan..."
    # - ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
    - echo "Starting Docker daemon..."
    - systemctl start docker
    - echo "Pre-script done."
  script:
    - echo "Entering source folder..."
    - cd nest-prisma-lab
    - echo "Creating .env..."
    - echo "DATABASE_URL=$DATABASE_URL\nJWT_SECRET=$JWT_SECRET" > .env
    - echo "Starting Build..."
    - docker compose build
    - echo "Tagging built image..."
    - docker tag nest-prisma-lab-app jarukitman/backend-project
    - echo "Logging into Dockerhub..."
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - echo "Pushing to Dockerhub..."
    - docker push $DOCKERHUB_REPO
    - echo "Deploying on the server..."
    - ssh "$SERVER_USER@$SERVER_HOST" "cd $SERVER_PATH; docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD; docker pull $DOCKERHUB_REPO; docker run $DOCKERHUB_REPO -d; docker logout"
    - echo "Script done."
