stages:
  - build
  - deploy

build:
  stage: build
  image: node:20-alpine
  before_script:
    - cd nest-prisma-lab
    - npm install
    - npx prisma db push --accept-data-loss
    - npx prisma generate
  script:
    - npm run build
deploy:
  stage: deploy
  image: node:alpine-20
  script:
    - node dist/src/main

