stages:
  - deploy

deploy_to_server:
  stage: deploy
  image: alpine
  before_script:
    - apk add --no-cache openssh-client bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    # - ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts
  script:
    - echo "Entering source folder..."
    - cd nest-prisma-lab
    - echo "Creating .env..."
    - echo "DATABASE_URL=$DATABASE_URL\nJWT_SECRET=$JWT_SECRET" > .env
    - echo "Deploying on the server..."
    - scp -r . "$SERVER_USER@$SERVER_HOST:$SERVER_PATH"
    - ssh "$SERVER_USER@$SERVER_HOST" "cd $SERVER_PATH; docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD; docker build --pull -t $DOCKERHUB_REPO; docker run $DOCKERHUB_REPO -d; docker push $DOCKERHUB_REPO; docker logout"
    - echo "Script done."
