services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment: # change to be your .env 
      DATABASE_URL: mysql://ict_admin:ict555@db:3306/ICTHotel?allowPublicKeyRetrieval=true
      JWT_SECRET: secretKey
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: mariadb:10.11
    environment: # change to be your sql user
      MARIADB_ROOT_PASSWORD: root 
      MARIADB_DATABASE: ICTHotel
      MARIADB_USER: ict_admin
      MARIADB_PASSWORD: ict555
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
  redis:
    image: redis
    ports:
      - '6379:6379'

volumes:
  mariadb_data:
